### ISSUE TITLE
Unexpected Filler

### ISSUE THREAD

**Issue by JavaCoffeePro** [ilyfairy/WebTranslate#11]
![image](https://user-images.githubusercontent.com/68426449/204291163-bc6cf2c8-5638-4e34-9134-07508c9edd13.png)

It may be caused by translate.google.com
Other tabs will fill with "ul" when the first tab fails to load translate.google.com. Others maybe get something wrong which them thought the failed tab is text area.

**Comment by ilyfairy** [comment]
fixed

**Comment by JavaCoffeePro** [comment]
Thanks
