### ISSUE TITLE
If you minimized window, It would never show up.

### ISSUE THREAD

**Issue by JavaCoffeePro** [ilyfairy/WebTranslate#6]
Well, I was still troubled near days. Now I knew the reason.
If you try to minimize the window. At the same time you setted AutoHide true. Your window would never show up again. Unless you restart the process. In that case, if you try to call out the window. You can still see the button on the taskbar. But the window doesn't exist anywhere.

**Comment by JavaCoffeePro** [comment]
Then, when you restart the process. The window size will change into zero.

**Comment by ilyfairy** [comment]
will be fixed soon
