### ISSUE TITLE
remove translate.google.cn?

### ISSUE THREAD

**Issue by JavaCoffeePro** [ilyfairy/WebTranslate#9]
Well, we all know translate.google.cn is unavailable now. But the problem is this program keeps translate.google.cn and it even still is default tab.
Maybe you can just remove it.

**Comment by ilyfairy** [comment]
removed

**Comment by JavaCoffeePro** [comment]
Well, to be honest. I think google translation is expected to be kept someway. But the problem is how to make it work again. At least we can't use the "translate.google.cn" now.

**Comment by ilyfairy** [comment]
use translate.google.com
